{{- if not .Values.controller.existingAdminSecret }}
{{- $secretName := include "jenkins.fullname" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
type: Opaque
data:
  jenkins-admin-user: {{ .Values.controller.adminUser | b64enc | quote }}
  {{- if $existing }}
  jenkins-admin-password: {{ index $existing.data "jenkins-admin-password" }}
  {{- else }}
  jenkins-admin-password: {{ .Values.controller.adminPassword | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
{{- end }}
